global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#evgeniy-sobolev'
