global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#evgeniy-sobolev'
