version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui
    image: ${USERNAME}/ui:${UI_V}
    ports:
      - ${UI_PORT}:${APP_PORT}/tcp
    networks:
      -  front-net

  post:
    image: ${USERNAME}/post
    image: ${USERNAME}/post:${POST_V}
    networks:
      - back-net
      - front-net

  comment:
    image: ${USERNAME}/comment
    image: ${USERNAME}/comment:${COMMENT_V}
    networks:
       - back-net
       - front-net

volumes:
  post_db:

networks:
  back-net:
  front-net:
