version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui
    image: ${USERNAME}/ui:${UI_V}
    environment:
      ZIPKIN_ENABLED: ${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    ports:
      - ${UI_PORT}:${APP_PORT}/tcp
    networks:
      - front-net
      - back-net

  post:
    image: ${USERNAME}/post
    image: ${USERNAME}/post:${POST_V}
    environment:
      ZIPKIN_ENABLED: ${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back-net
      - front-net

  comment:
    image: ${USERNAME}/comment
    image: ${USERNAME}/comment:${COMMENT_V}
    environment:
      ZIPKIN_ENABLED: ${ZIPKIN_ENABLED}
    networks:
       - back-net
       - front-net

volumes:
  post_db:

networks:
  back-net:
  front-net:
