---
  apiVersion: v1
  kind: Service
  metadata:
    name: ui
    labels:
      app: reddit
      component: ui
  spec:
    type: NodePort
    ports:
      - #nodePort: 32092 # порт для доступа снаружи кластера
        port: 9292
        protocol: TCP
        targetPort: 9292
    selector:
      app: reddit
      component: ui
